---
- hosts: all
  become_user: root
  become_method: sudo
  become: true
  tasks:
    - name: Install CherryPy
      yum:
        name: python-cherrypy
        state: latest
        update_cache: yes

    - name: "Run basic unittest for CPUInfo"
      command: /usr/bin/python2.7 /vagrant/test_cpuinfo.py
      args:
        chdir: /tmp

    - name: copy cpuinfo_svc.py to vm
      copy:
        src: cpuinfo_svc.py
        dest: /usr/local/bin/cpuinfo_svc.py
        mode: u=rwx,g=rw,o=r

    - name: copy cpuinfo.service to vm
      copy:
        src: cpuinfo.service
        dest: /etc/systemd/system/cpuinfo.service

    - name: Ensure cpuinfo is running
      systemd:
        name: cpuinfo
        enabled: yes
        state: restarted
        daemon_reload: yes
